language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules
install:
  - npm install

script:
  - npm run generate
  - bash deploy.sh

branches:
  only:
    - master

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "pc.poisoning@gmail.com"
